### ISSUE TITLE
Error when loading default profile

### ISSUE THREAD

**Issue by marcomastri** [eweracs/HTLSManager#6]
Glyph Version 3.1.1 (3136)
This is what I get when loading the default profile, or I try to import a config file:

```
Dettagli:Traceback (most recent call last):

  File "vanillaBase.py", line 514, in action_
    self.callback(sender)

  File "plugin.py", line 1167, in load_profile
    self.rebuild_font_rules(new_rules)

  File "plugin.py", line 691, in rebuild_font_rules
    self.add_font_rule(rule_id, category, font_rules=new_rules)

  File "plugin.py", line 587, in add_font_rule
    getattr(self.fontRulesTab, category).stackView.appendView(

AttributeError: 'VanillaTabItem' object has no attribute 'Letter'

App:3.1.1-3136 Plugin:(null)-(null)
```

**Comment by eweracs** [comment]
Hello, thanks a lot for the report, I merged some changes by accident. It should be fixed now.
